[project]
name = "ac2-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.121.3",
    "numpy>=2.3.5",
    "pymongo>=4.15.4",
    "scipy>=1.16.3",
]
